- docs/source/contribute/dev_contribute.rst
- docs/source/contribute/doc_contribute.rst
- docs/source/development/code_review.rst
- docs/source/development/commit_message.rst
- docs/source/development/patch.rst
Removing Gerrit from our workflow.
> MOTECH-1886 Update documentation with GitHub information

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/repository/TaskActivitiesDataService.java
- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- modules/tasks/tasks/src/main/resources/webapp/partials/history.html
Now user can filter task activity by the type (warning, error, Success). When type is ERROR user
have possibility to display stack trace. This commit also removes Lookup annotation from countByTaskAndActivityTypes method to avoid error in the log.
> MOTECH-1894: Filter in the task history

- platform/server-bundle/src/main/java/org/motechproject/server/web/controller/DashboardController.java
- platform/server-bundle/src/main/resources/webapp/js/directives.js
Cherry pick of this commit to the 0.26.X branch
> MOTECH-1772 QUERY - Server local time is static

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
- platform/mds/mds-web/src/main/resources/webapp/js/directives.js
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/entityInstances.html
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/history.html
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/Entity.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/EntityServiceImpl.java
Now when field is nonDisplayable then column in the grid is not generated
and this field cannot be selected in the 'fields' multiselect.
> MOTECH-1906: Hidden field should not be selected on the button fields

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/Task.java
- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
- platform/mds/mds-web/src/main/resources/webapp/js/directives.js
- platform/mds/mds-web/src/main/resources/webapp/partials/embeddedMdsFilters.html
- platform/mds/mds-web/src/main/resources/webapp/partials/modals/partials/dataBrowsing.html
- platform/mds/mds-web/src/main/resources/webapp/partials/tabLayoutWithMdsGrid.html
- platform/mds/mds/src/main/java/org/motechproject/mds/annotations/internal/EntityProcessor.java
- platform/mds/mds/src/main/java/org/motechproject/mds/annotations/internal/FieldProcessor.java
- platform/mds/mds/src/main/java/org/motechproject/mds/annotations/internal/UIFilterableProcessor.java
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/Entity.java
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/EntityDraft.java
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/Field.java
- platform/mds/mds/src/main/java/org/motechproject/mds/dto/FieldDto.java
- platform/mds/mds/src/main/java/org/motechproject/mds/osgi/MdsBundleWatcher.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/EntityServiceImpl.java
- platform/mds/mds/src/test/java/org/motechproject/mds/annotations/internal/UIFilterableProcessorTest.java
@UIFilterable annotation now works. Also changed the name of the MdsEmbeddedCtrl to MdsEmbeddableCtrl.
> MOTECH-1901: Fixed @UIFilterable annotation

- platform/mds/mds/src/main/java/org/motechproject/mds/builder/impl/EntityMetadataBuilderImpl.java
fix for cascade delete in 1:N unidirectional relationship
> MOTECH-1838: Cascade delete is not working for unidirectional

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
This commits repairs invisible map inputs. Now user can add/delete rows in the map field and can
see options in the combobox list.
> MOTECH-1915: Map field in MDS embedded UI

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
This commits repairs invisible map inputs. Now user can add/delete rows in the map field and can
see options in the combobox list.
>  MOTECH-1915: Map field in MDS embedded UI

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/annotations/TaskAnnotationBeanPostProcessor.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/json/ActionEventRequestDeserializer.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/osgi/ChannelServiceRegistrationListener.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/osgi/TasksBlueprintApplicationContextTracker.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskActionExecutor.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskContext.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskFilterExecutor.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskInitializer.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskTriggerHandler.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskDataProviderServiceImpl.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskServiceImpl.java
This commit adds more logging in tasks.
> MOTECH-1897: Adds more logging in tasks

- platform/mds/mds/src/main/resources/db/migration/default/V42__MOTECH-1411.sql
Fixed postgresql INSERT statements in V42 migration in MDS module.
> MOTECH-1411: Fix for postgresql V42 migration in MDS

- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/controller/InstanceController.java
- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/util/QueryParamsBuilder.java
- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/controller/InstanceControllerTest.java
- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/QueryParamsBuilderTest.java
- platform/mds/mds/src/main/java/org/motechproject/mds/query/QueryParams.java
- platform/mds/mds/src/main/java/org/motechproject/mds/util/Order.java
* lookups are order based on their fields default
* moved query param building code to a separate util
> MOTECH-1931: Made ordering even more consistent

- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/ExampleData.java
- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/controller/EntityControllerTest.java
- platform/mds/mds/src/main/java/org/motechproject/mds/dto/DraftData.java
- platform/mds/mds/src/main/java/org/motechproject/mds/dto/FieldDto.java
Now the EntityControllerTest is using the Spring Mock MVC.
> MOTECH-1924: Refactor EntityControllerTest

- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/controller/InstanceController.java
- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/domain/EntityRecord.java
- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/InstanceService.java
- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java
- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/controller/InstanceControllerTest.java
- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/service/impl/InstanceServiceTest.java
- platform/mds/mds/src/main/java/org/motechproject/mds/dto/FieldDto.java
- platform/mds/mds/src/main/java/org/motechproject/mds/ex/object/ObjectReadException.java
The method now returns what other methods return - values
packages as EntityRecords.
> MOTECH-1628: Updated the methods for related instance retrieval

- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/controller/EntityController.java
- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/controller/EntityControllerTest.java
- platform/mds/mds/src/main/java/org/motechproject/mds/repository/AllEntities.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/EntityService.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/EntityServiceImpl.java
- platform/mds/mds/src/test/java/org/motechproject/mds/it/service/EntityServiceContextIT.java
Now we can retrieve all entities by bundle symbolic name. This change will
improve performance of embedded UI in mTraining module.
> MOTECH-1388: Added listEntitiesByBundle

- platform/mds/mds-web/pom.xml
- platform/mds/mds-web/src/main/resources/webapp/css/mds.css
- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
- platform/mds/mds-web/src/main/resources/webapp/js/directives.js
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/entityInstances.html
- platform/server-bundle/src/main/resources/webapp/css/index.css
- platform/server-bundle/src/main/resources/webapp/css/jqGrid/ui.jqgrid.override.css
- platform/server-bundle/src/main/resources/webapp/js/common.js
*From now, a user can see vertical scroll of the jqgrid  even then display many records 
and cells have a large number of strings.
*Optimized CSS classes
> MOTECH-1937 Header and footer of the jqGrid always visible.

- pom.xml
Worth trying this out before doing the 0.27 release
> MOTECH-1943: Updated release plugin version to 2.5.2

- platform/mds/mds/src/main/java/org/motechproject/mds/repository/ComboboxValueRepository.java
- platform/mds/mds/src/test/java/org/motechproject/mds/it/osgi/MdsBundleIT.java
- platform/mds/mds/src/test/java/org/motechproject/mds/it/reposistory/ComboboxValueRepositoryContextIT.java
* Added ordering to retrieval of options.
They will be returned alphabetically.
> Fix combobox tests on PostgreSQL

- docs/source/get_started/model_data/model_data.rst
I've added a short documentation listing some most common
problems spotted, while using relationships in MDS. It has
a form of problem/explanation. New entries can be added
at any point of time.
> MOTECH-1680 MDS docs - common problems with relationships

- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
A function that parse exception message, needs to have additional parameters in table to parse message correctly.
> MOTECH-1952 Parse exception message correctly

- platform/web-security/src/main/java/org/motechproject/security/domain/MotechUser.java
- platform/web-security/src/main/java/org/motechproject/security/event/PasswordExpirationCheckEventHandler.java
- platform/web-security/src/main/java/org/motechproject/security/service/authentication/MotechAuthenticationProvider.java
- platform/web-security/src/test/java/org/motechproject/security/domain/MotechUserTest.java
- platform/web-security/src/test/java/org/motechproject/security/email/impl/EmailSenderImplTest.java
- platform/web-security/src/test/java/org/motechproject/security/event/PasswordExpirationCheckEventHandlerTest.java
- platform/web-security/src/test/java/org/motechproject/security/event/PasswordReminderEventHandlerTest.java
Now when the lastPasswordChange is null the modificationDate field will be used.
> MOTECH-1972: Password Reminder - 500 Internal Server Error

- platform/mds/mds-test-bundle/src/test/java/org/motechproject/mds/test/osgi/MdsDdeBundleIT.java
MdsDdeBundleIT completely resets state
> MOTECH-1855: MdsDdeBundleIT completely resets state

- platform/server-bundle/src/main/resources/webapp/js/common.js
Added callback functions to add/remove .active state for ui-layout-button-toggle buttons.
> Filter button active state

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
* Removed an 'if' condition in the mouseup function for the 'document'
> MOTECH-1969: Clicking the drop down button should close the lookup panel

- platform/mds/mds/src/main/java/org/motechproject/mds/builder/impl/EntityMetadataBuilderImpl.java
Came up after changes to use dtos
> Fixed issue with setting length for TEXT columns in MDS

- docs/source/get_started/configure_hipaa.rst
This doc focuses primarily on the security rule - technical safeguards in particular, since they apply to the MOTECH part of an implementation. The privacy rule is mentioned. I do not dive into adminstrative
stuff and other requirements.
> MOTECH-931: Documentation for configuring MOTECH to be HIPAA compliant

- platform/web-security/src/main/java/org/motechproject/security/event/PasswordExpirationCheckEventHandler.java
Conflicts:
platform/web-security/src/main/java/org/motechproject/security/event/PasswordExpirationCheckEventHandler.java
> MOTECH-2002: Fixed logging and var names in reminder handling

- modules/admin/src/main/resources/webapp/index.html
There was an error generated by incorrect syntax in the index.html partial where breadcrumbs are created.
> Admin javascript error

- docs/source/demos/hello_world.rst
The import statement was missing for the `@Component`
> Add Component import to HelloWorldEventHandler

- platform/mds/mds-web/src/main/resources/META-INF/motech/mdsWebContext.xml
- platform/mds/mds-web/src/main/resources/webapp/index.html
- platform/mds/mds-web/src/main/resources/webapp/messages/messages.properties
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/mds-settings.html
- platform/mds/mds/src/main/java/org/motechproject/mds/config/ModuleSettings.java
- platform/mds/mds/src/main/java/org/motechproject/mds/config/SettingsService.java
- platform/mds/mds/src/main/java/org/motechproject/mds/config/impl/SettingsServiceImpl.java
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/BundleFailureReport.java
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/BundleRestartStatus.java
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/ConfigSettings.java
- platform/mds/mds/src/main/java/org/motechproject/mds/repository/AllBundleFailureReports.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/MdsOsgiBundleApplicationContextListener.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/JarGeneratorServiceImpl.java
- platform/mds/mds/src/main/java/org/motechproject/mds/util/Constants.java
- platform/mds/mds/src/main/resources/META-INF/spring/blueprint.xml
- platform/mds/mds/src/main/resources/db/migration/default/V44__MOTECH-2018.sql
- platform/mds/mds/src/main/resources/db/migration/mysql/V44__MOTECH-2018.sql
- platform/mds/mds/src/main/resources/motech-mds.properties
- platform/mds/mds/src/test/java/org/motechproject/mds/config/ModuleSettingsTest.java
- platform/mds/mds/src/test/java/org/motechproject/mds/config/impl/SettingsServiceImplTest.java
- platform/mds/mds/src/test/java/org/motechproject/mds/it/BaseIT.java
- platform/mds/mds/src/test/java/org/motechproject/mds/it/MdsContextIntegrationTests.java
- platform/mds/mds/src/test/java/org/motechproject/mds/it/reposistory/AllBundleFailsReportsContextIT.java
- platform/mds/mds/src/test/java/org/motechproject/mds/service/MdsOsgiBundleApplicationContextListenerTest.java
- platform/osgi-platform/src/main/java/org/motechproject/server/osgi/status/PlatformStatusManagerImpl.java
Now when refreshing of the module will fail then MDS will automatically restart it.
Style of the Mds settings page was changed in this pull request (now it looks like settings from the Admin module).
> MOTECH-2018: Module restarted after failing

- platform/mds/mds/src/main/java/org/motechproject/mds/service/ActionHandlerService.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/DefaultMotechDataService.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/ActionHandlerServiceImpl.java
- platform/mds/mds/src/main/resources/velocity/templates/task-channel-template.vm
- platform/mds/mds/src/test/java/org/motechproject/mds/service/impl/ActionHandlerServiceImplTest.java
Create or update from MDS is now available as a task action.
> MOTECH-2029: Added MDS upsert as a task action

- platform/mds/mds-web/src/test/java/org/motechproject/mds/web/it/MdsRestBundleIT.java
* Removed multiple HTTP calls to startup
* Removed unused code
* Added logging
> MOTECH-1961: Fixed a few MdsRestBundleIT issues

- platform/mds/mds/src/main/java/org/motechproject/mds/jdo/MdsJdoAnnotationReader.java
This reverts commit 7b422034917e1686a7b808d4601f59bf873ade85. 
The change introduced build failures in modules repo.
> Revert "MOTECH-2035: Fixes bug after schema regeneration in MDS"

- docs/source/roadmap.rst
Submitting this patch to get the conversation started. Do not merge this code until the team reviews and agrees on the roadmap.
> MOTECH-2064 Updating MOTECH roadmap

- modules/admin/pom.xml
The API was already cleaned up. I only ordered exports
alphabetically.
> MOTECH-2079: Reorder exports in the admin module

- platform/commons-date/pom.xml
- platform/commons-date/src/main/java/org/motechproject/commons/date/exception/ParseException.java
- platform/commons-date/src/main/java/org/motechproject/commons/date/model/DayOfWeek.java
- platform/commons-date/src/main/java/org/motechproject/commons/date/model/Time.java
- platform/commons-date/src/test/java/org/motechproject/commons/date/model/TimeTest.java
* Removed redundant ',' in pom
* Added a few javadocs
* Removed confusing and duplicating methods in Time
> MOTECH-2082: Clean up commons-date API

- ui/src/js/common.js
Changed $.blockUI css border property so the default border is removed from the element.
> MOTECH-2127 Fix blockUI window

- platform/web-security/src/main/resources/webapp/js/controllers.js
- platform/web-security/src/main/resources/webapp/js/directives.js
- platform/web-security/src/main/resources/webapp/partials/role.html
Delete role button was available because addOrEdit variable wasnt checked in few divs in html.
Added checking for it.
> MOTECH-2099: Removed Delete role buton while adding new role

- platform/server/src/main/webapp/static/js/bootstrap-page.js
- ui/bower.json
The login page in IE9 caused the UI to constantly refresh. Updating Angular.js to version 1.2.29 fixed the problem. I also changed variable names from 'const' to 'var' because 'const' isn't supported below IE11.
> MOTECH-2104 IE9 Automatically Refreshing on login page

- docs/source/development/dev_setup/dev_install.rst
Added sudo for consistency in dev installation docs
> Added missing sudo to docs

- platform/mds/mds-web/pom.xml
- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/exception/InvalidParameterException.java
- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/rest/MdsRestController.java
- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/rest/ParamParser.java
MDS Web was exporting all packages contained in it. added <Export-Package> to export only web.service and web.domain used by ebodac.
> MOTECH-2093: Changed mds-web/pom.xml to export only necessary packages

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerServiceImpl.java
Slight refactor of said class to improve readability of the following PR.
> MOTECH-2063: Refactor of the MotechSchedulerServiceImpl class

- pom.xml
We will make UITestFramework use motech as a parent so it can
manage the dependencies for it. These are the conflicting deps.
> Added management for some dependencies, included FTs in pom

- platform/server-bundle/src/main/resources/webapp/WEB-INF/jsp/loginPage.jsp
Logging in should now work properly after first failed attempt.
> MOTECH-2206 Fixed login retry page [0.28.X]

- platform/server-bundle/src/main/resources/webapp/WEB-INF/jsp/loginPage.jsp
Logging in should now work properly when retrying as well.
> MOTECH-2206 Fixed login retry page

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
Fixed not hiding modal window while creating a new entity. Adding and importing new entities takes around 20-30 sec.
> MOTECH-2189: MOTECH modal not hiding after create/import new entities

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/exception/MotechSchedulerException.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerServiceImpl.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/validation/SchedulableJobValidator.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/web/controller/JobsController.java
- modules/scheduler/scheduler/src/main/resources/webapp/js/controllers.js
- modules/scheduler/scheduler/src/main/resources/webapp/js/services.js
- modules/scheduler/scheduler/src/main/resources/webapp/messages/messages.properties
- modules/scheduler/scheduler/src/main/resources/webapp/partials/createJob.html
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerServiceImplBundleIT.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/validation/SchedulableJobValidatorTest.java
- ui/src/js/directives.js
Added server side validation of the created jobs along with error notifications on the UI.
> MOTECH-2063: Improved UI for the Job creation in the Scheduler module

- modules/admin/pom.xml
- modules/admin/src/test/java/org/motechproject/admin/it/AdminBundleIT.java
- modules/admin/src/test/resources/log4j.xml
- modules/testing-utils/upload-test-bundle/pom.xml
- modules/testing-utils/upload-test-bundle/src/main/java/org/motechproject/testing/uploadtestbundle/UploadTestBundle.java
- pom.xml
First IT, only for Repository.
> MOTECH-1450 IT for adding modules at runtime through the Admin UI. Just for Repository

- modules/scheduler/scheduler/src/main/resources/webapp/js/directives.js
- modules/scheduler/scheduler/src/main/resources/webapp/partials/createJob.html
- platform/mds/mds-web/src/main/resources/webapp/js/directives.js
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-basic-defaultValue-period.html
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-edit-Value-period.html
The common period modal directive does not work after
going through JS minification. Until this is
resolved (MOTECH-2265) I added the modals to
Scheduler and MDS, so they work properly.
> MOTECH-2063 Added period modals to Scheduler and MDS

- docs/source/development/browser.rst
This PR is connected with https://github.com/motech/motech/pull/408
I had to open new PR from my fork to push my changes. This PR includes corrections after review.
> MOTECH-2211: Documentation for IE9 issues

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/builder/SchedulableJobBuilder.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/DayOfWeekJobId.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/DayOfWeekSchedulableJob.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/exception/CronExpressionException.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerServiceImpl.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/util/CronExpressionUtil.java
- modules/scheduler/scheduler/src/main/resources/webapp/js/controllers.js
- modules/scheduler/scheduler/src/main/resources/webapp/js/directives.js
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerDatabaseServiceImplBundleIT.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerServiceImplBundleIT.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/util/CronExpressionUtilTest.java
Separated DayOfWeek job and fixed some issues with job edition
> MOTECH-2063: Separated DayOfWeek job

- modules/admin/pom.xml
- modules/admin/src/test/java/org/motechproject/admin/it/AdminBundleIT.java
- modules/admin/src/test/java/org/motechproject/admin/it/ModuleInstallFT.java
The IT was turned into an FT that will run
only in the FT profile. For now this is acceptable.
> Move AdminBundleIT to a separate profile

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/builder/SchedulableJobBuilder.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/constants/SchedulerConstants.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/DayOfWeekJobId.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/DayOfWeekSchedulableJob.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/exception/CronExpressionException.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/exception/MotechSchedulerException.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerServiceImpl.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/util/CronExpressionUtil.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/validation/SchedulableJobValidator.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/web/controller/JobsController.java
- modules/scheduler/scheduler/src/main/resources/webapp/index.html
- modules/scheduler/scheduler/src/main/resources/webapp/js/controllers.js
- modules/scheduler/scheduler/src/main/resources/webapp/js/directives.js
- modules/scheduler/scheduler/src/main/resources/webapp/js/services.js
- modules/scheduler/scheduler/src/main/resources/webapp/messages/messages.properties
- modules/scheduler/scheduler/src/main/resources/webapp/partials/createJob.html
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerDatabaseServiceImplBundleIT.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerServiceImplBundleIT.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/util/CronExpressionUtilTest.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/validation/SchedulableJobValidatorTest.java
- platform/email/src/main/resources/webapp/index.html
- platform/mds/mds-web/src/main/resources/webapp/js/directives.js
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-basic-defaultValue-period.html
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-edit-Value-period.html
- ui/src/js/directives.js
This pull request contains fixes for the Scheduler module, taken from the master branch after QA testing.
> MOTECH-2063 Moved Scheduler fixes to 0.28.X

- modules/admin/src/main/resources/webapp/partials/bundleSettings.html
I changed implementation angular object "module.bundleId" in bundleSettings.html, because of it was seen like string, not like angular object.
> MOTECH-2258: Fixed HTTP-500 when submitting json-file in module settings

- platform/event/src/main/java/org/motechproject/event/listener/proxy/EventAnnotationBeanPostProcessor.java
- platform/event/src/test/java/org/motechproject/event/it/EventHandlerAnnotationProcessorBundleIT.java
- platform/event/src/test/java/org/motechproject/event/osgi/TestHandlerProxied.java
- platform/event/src/test/resources/META-INF/spring/testEventBundleContext.xml
Information about this issue you can find here : https://github.com/motech/motech/pull/437
> MOTECH-2297: Prevents double listener registration for proxied beans [0.27.X]

- platform/event/src/main/java/org/motechproject/event/listener/proxy/EventAnnotationBeanPostProcessor.java
- platform/event/src/test/java/org/motechproject/event/it/EventHandlerAnnotationProcessorBundleIT.java
- platform/event/src/test/java/org/motechproject/event/osgi/TestHandlerProxied.java
- platform/event/src/test/resources/META-INF/spring/testEventBundleContext.xml
Information about this issue you can find here : https://github.com/motech/motech/pull/437
> MOTECH-2297: Prevents double listener registration for proxied beans [0.28.X]

- checkstyle.xml
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/RepeatingJobId.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/RunOnceJobId.java
- platform/mds/mds-test-bundle/src/main/java/org/motechproject/mds/test/domain/differentbundles/EntityC.java
- platform/mds/mds-test-bundle/src/main/java/org/motechproject/mds/test/domain/inheritancestrategies/PetOwner.java
- platform/mds/mds-test-bundle/src/main/java/org/motechproject/mds/test/domain/inheritancestrategies/Truck.java
- platform/mds/mds-test-bundle/src/main/java/org/motechproject/mds/test/domain/inheritancestrategies/VehicleOwner.java
- platform/mds/mds-test-bundle/src/main/java/org/motechproject/mds/test/domain/validation/ValidationSample.java
- utils/archetypes/http-bundle-archetype/src/test/resources/projects/basic/archetype.properties
- utils/archetypes/minimal-bundle-archetype/src/test/resources/projects/basic/archetype.properties
- utils/archetypes/repository-bundle-archetype/src/test/resources/projects/basic/archetype.properties
- utils/archetypes/settings-bundle-archetype/src/test/resources/projects/basic/archetype.properties
> MOTECH-2269 Add new checkstyle - @RedundantImport check.

- modules/admin/src/main/resources/webapp/js/controllers.js
- modules/admin/src/main/resources/webapp/partials/bundles.html
Four missing modules have been added to the dropdown list for install
from repository. Moreover, the install button will no longer work if
no module or file was selected.
> Added missing modules to repository install

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
- platform/mds/mds-web/src/main/resources/webapp/partials/dataBrowser.html
- platform/mds/mds-web/src/main/resources/webapp/partials/schemaEditor.html
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/entityInstances.html
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/fields.html
These changes are connected with https://github.com/motech/UITestFramework/pull/3
> MOTECH-2034 Add id property for fields and buttons used in Selenium Test

- platform/mds/mds/src/main/java/org/motechproject/mds/dto/TypeDto.java
- platform/mds/mds/src/main/resources/db/migration/default/V5__MOTECH-2324.sql
- platform/mds/mds/src/main/resources/db/migration/mysql/V5__MOTECH-2324.sql
- database is migrated to version-5
> MOTECH-2324: Changed the default name of Character from 'char' to 'character'

- platform/mds/mds/src/main/java/org/motechproject/mds/listener/records/BaseListener.java
MDS BaseListeners will now try to retrieve entities bundle context from the bundle context before waiting for the notification.
> MOTECH-2298: Changed the way BaseListeners retrieve application context [0.28.X]

- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java
The fetch time of 100 instances of the Participant went down from ~9 sec. to ~0.2 sec.
> MOTECH-2306: Optimized a few methods in the InstanceServiceImpl class

- modules/admin/src/main/resources/webapp/js/controllers.js
* motech-metrics -> metrics
* added ihe-interop
> Updated the module list in admin

- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
User now can select year and month from the tasks datepicker
> Motech-2274: Added provision to change year and month in the tasks datepicker

- modules/tasks/tasks/src/main/resources/webapp/css/tasks.css
- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/partials/history.html
Task name in Task History is shortened only if there is not enough space in a line.
> MOTECH-2299: Fixed shortened task name in Task History in Task module

- modules/admin/src/main/java/org/motechproject/admin/web/controller/BundleAdminController.java
- modules/admin/src/test/java/org/motechproject/admin/it/ModuleInstallFT.java
* Fixed wrong param name
* Better error handling
> Fixed AdminFT failure

- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerDatabaseServiceImplBundleIT.java
Since the bug isn't reproducible on master, I only added integration test for RepeatingPeriodJob in MotechSchedulerDatabaseServiceImplBundleIT.java.
> MOTECH-2350: Add integration test for RepeatingPeriodJob in Scheduler

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerDatabaseServiceImpl.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerDatabaseServiceImplBundleIT.java
Fixed condition in MotechSchedulerDatabaseServiceImpl.java.
> MOTECH-2350: Fixed retrieving detail about RepeatingPeriodJob in Scheduler [0.27.X]

- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
Made changes to the tasks datepicker
> Motech-2274 : User can select year and month in the datepicker

- platform/mds/mds/src/main/java/org/motechproject/mds/json/FieldReader.java
Now entities with relationships can be imported without any problem
> Motech-2358 Fixed the bug related to importing entities

- modules/admin/src/main/resources/webapp/partials/bundleSettings.html
- platform/server-config/src/main/java/org/motechproject/config/service/impl/ConfigurationServiceImpl.java
MOTECH-2258 and MOTECH-2264 have been resolved in master, but remain in 0.28. I cherry-picked these commits to the 0.28.X branch so they don't remain when it's released.
> Cherry-picking two commits that cause errors in Admin module

- pom.xml
Fixed javadoc parsing for the release build.
> MOTECH-2469: Fixed Java 8 javadoc issue

- modules/tasks/tasks/src/main/resources/webapp/partials/form-filter.html
Fixed parameter for function findObject in ng-repeat responsible for listing Object Fields in Tasks filter. It was 'ds.providerId' and should be 'ds.providerName'.
Additionally removed redundant spacers for cleaner look of the code.
> MOTECH-2453: Fixed empty provider field in Tasks filters in Tasks

- modules/scheduler/scheduler/src/main/resources/webapp/js/app.js
- modules/scheduler/scheduler/src/main/resources/webapp/js/controllers.js
- modules/scheduler/scheduler/src/main/resources/webapp/partials/createJob.html
- modules/scheduler/scheduler/src/main/resources/webapp/partials/scheduler.html
Fixed creating link with action parameter ("new"/"edit") when calling page responsible for creating and updating Schedule jobs.
> MOTECH-2467: Fixed missing button for creating schedule job in Scheduler

- docs/source/deployment/CORS_Headers.rst
Now code blocks on docs.motechproject.org should be visible.
> MOTECH-2188: Fixed code blocks

- modules/scheduler/scheduler/src/main/resources/webapp/partials/createJob.html
- platform/email/src/main/resources/webapp/partials/settings.html
- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/mds-settings.html
I make changes reported in https://applab.atlassian.net/browse/MOTECH-2207
> MOTECH-2207 Change reported buttons

- modules/admin/src/main/resources/webapp/js/controllers.js
Continuation of this ticket: https://github.com/motech/modules/pull/293
> MOTECH-2364: Renamed openmrs19 module to openmrs.

- platform/server/pom.xml
- platform/server/src/main/java/org/motechproject/server/bootstrap/BootstrapController.java
- platform/server/src/main/java/org/motechproject/server/bootstrap/MessageBrokerPingService.java
- platform/server/src/main/java/org/motechproject/server/bootstrap/MessageBrokerPingServiceImpl.java
- platform/server/src/main/resources/messages/messages.properties
- platform/server/src/main/webapp/WEB-INF/jsp/bootstrapconfig.jsp
- platform/server/src/main/webapp/static/js/bootstrap-page.js
- platform/server/src/test/java/org/motechproject/server/bootstrap/BootstrapControllerTest.java
- platform/server/src/test/java/org/motechproject/server/it/MessageBrokerPingServiceIT.java
- pom.xml
- ui/src/css/bootstrap-page.scss
Motech -1605.
Added the "Verify AMQ Connection" button which checks the Active Mq connection and also displays error message when connection is not established.
> MOTECH-1605 MOTECH startup should detect if ActiveMQ is working

- modules/scheduler/scheduler/src/test/resources/performanceTestSchedulerApplicationContext.xml
- platform/config-core/src/main/resources/META-INF/motech/coreConfigContext.xml
- platform/config-core/src/main/resources/META-INF/spring/coreConfigBundleContext.xml
- platform/event/src/main/resources/META-INF/motech/activemqConnection.xml
- platform/event/src/main/resources/META-INF/motech/eventConsumers.xml
- platform/event/src/main/resources/META-INF/motech/eventPublishers.xml
- platform/event/src/main/resources/META-INF/spring/eventContext.xml
- platform/event/src/test/resources/META-INF/spring/testEventBundleContext.xml
- platform/osgi-web-util/src/test/resources/META-INF/spring/testWebUtilApplicationContext.xml
- platform/osgi-web-util/src/test/resources/testWebUtilApplication.xml
- platform/server-config/src/main/resources/META-INF/motech/applicationPlatformConfig.xml
- platform/server-config/src/main/resources/META-INF/motech/configContext.xml
- platform/server-config/src/main/resources/META-INF/spring/applicationPlatformConfigBundle.xml
- platform/server-config/src/test/resources/testApplicationPlatformConfig.xml
- platform/server/src/main/resources/META-INF/motech/applicationPlatformServer.xml
- platform/server/src/main/webapp/WEB-INF/bootstrap-servlet.xml
- platform/server/src/test/resources/testPlatformServerApplicationContext.xml
I think, the problem was with schemaLocation. If a version is not specified before suffix then we gets the latest version (actually 4.2).
> MOTECH-2525: Fixed: Random web-security failure in spring 3.2

- platform/server-bundle/src/main/resources/webapp/js/controllers.js
After adding state provider there was an url parsing error and angular couldn't find proper state
> fix entering module settings in admin module

- ui/src/js/directives.js
changed transclude from true to false in motechFileUpload directive
> Motech-2401  Fixed the transclusion issue in the Tasks module

- platform/mds/mds/src/main/resources/db/migration/mysql/V1__Base_version.sql
flywayMigrationVersion should be auto incremented while new migration is added.
> Fixed module migrations.

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskActionExecutor.java
Added a null exception if condition for convertToList method.
> MOTECH-2075 Tasks Module: NPE when parsing a null list

- platform/mds/mds/src/main/resources/db/migration/default/V6__MOTECH-2578.sql
- platform/mds/mds/src/main/resources/db/migration/mysql/V1__Base_version.sql
- platform/mds/mds/src/main/resources/db/migration/mysql/V6__MOTECH-2578.sql
At first I added auto-increment in base version, but it should be placed in a separate migration. In PSQL I used sequence. I looked for solution with adding 'serial' to existing field in table, like in MySQL, but I have found only this.
> Added new migration to fixed module migrations feature.

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- modules/tasks/tasks/src/main/resources/webapp/partials/form-filter.html
After task [field bubbles refactor](https://github.com/motech/motech/pull/357/files) the old string manipulations directives were removed and new functionality wasn't added to filters.
> MOTECH-2542: fix string manipulations in task module for task filters

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskActionExecutor.java
KeyEvaluator holds the current task state - the task context, yet it
was stored as a variable by the task action executor which is a
Sprint singleton. This would cause concurrency issues.
> MOTECH-2622: Fixed concurrency issue in tasks

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/OperatorType.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/util/TaskFilterExecutor.java
- modules/tasks/tasks/src/main/resources/webapp/js/util.js
- modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
> Changed 'EXISTS' of boolean to 'IS TRUE'

- platform/mds/mds/src/main/java/org/motechproject/mds/dbmigration/java/V47__MOTECH1269.java
Now it supports db mode - lowercase for table names.
> MOTECH-1269: Improved history db migration

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/listener/MotechSchedulerListener.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/MotechScheduledJob.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerDatabaseServiceImpl.java
- modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerDatabaseServiceImplBundleIT.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskTriggerHandler.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskTriggerHandlerTest.java
- platform/event/src/main/java/org/motechproject/event/MotechEvent.java
- display metadata as list, not as one parameter
- fix parsing metadata in task module and while executing job
- add test to check if job is UI defined
> MOTECH-2601: fix and tests for adding event metadata in scheduler module

- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
> Motech-2439 Added year range for tasks datepicker

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/listener/MotechSchedulerListener.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/MotechScheduledJob.java
- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerServiceImpl.java
- also changed removing scheduler parameters from event metadata
> MOTECH-2601: fix scheduling repeating period job

- modules/tasks/tasks/src/main/resources/webapp/partials/form-data-source.html
disable Object drop-down list before selecting Source from drop-down list
> MOTECH-2553 disable Object drop-down list

- modules/admin/src/main/resources/webapp/messages/messages.properties
MOTECH-2667 Migrate admin server log to MOTECH UI 
- added key message for 'Log file'
> MOTECH-2667 Migrate admin server log to MOTECH-UI

- platform/server/pom.xml
- pom.xml
On server was no XML parsing library. That's why commcare request was causing response code 500.
> MOTECH-2720: Added XML parser library to server

- platform/server/pom.xml
- pom.xml
* MOTECH-2720: Added XML parser library to server
* MOTECH-2720: Added dependency version to main pom
> MOTECH-2720: 0.29.X - Fixed Commcare - Data Forwarding 500 Status

- platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/EntityServiceImpl.java
- platform/mds/mds/src/main/resources/db/migration/default/V8__MOTECH-2713.sql
- platform/mds/mds/src/main/resources/db/migration/mysql/V8__MOTECH-2713.sql
https://github.com/motech/motech/pull/633
> cherry-pick MOTECH-2713: Error during creating new entity

- modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/web/controller/JobsController.java
- modules/scheduler/scheduler/src/main/resources/webapp/js/services.js
Changed URL to use GET, not POST, to fetch data from the server
> MOTECH-2783 Scheduler getJob in GET

- platform/web-security/src/main/java/org/motechproject/security/web/controllers/UserController.java
- platform/web-security/src/main/resources/webapp/js/controllers.js
Changed URL to use GET, not POST, to fetch data from the server
> MOTECH-2782 Web-Security getUser in GET

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- platform/server-bundle/src/main/resources/webapp/js/services.js
- ui/bower.json
Fixed problem with reopening modal window - manipulation string tasks
Fixed problem with reopening modal window - MOTECH-2300 Improve tasks history UI
Update Bootstrap3-dialog plug-in to version 1.35.2
> MOTECH-2718 Ghost of closed modal window

- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- platform/server-bundle/src/main/resources/webapp/js/services.js
- ui/bower.json
Fixed problem with reopening modal window - manipulation string tasks
Enhanced BootstrapDialogManager service
Update Bootstrap3-dialog plug-in to version 1.35.2
> MOTECH-2718 Ghost of closed modal window for 0.29.X

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
Fixed unwanted blocking of ui
Fixed modal which didn`t close when we go back to previous site
> MOTECH-2785: Fixed unwanted blocking of the ui in MDS

- utils/archetypes/minimal-bundle-archetype/src/main/resources/archetype-resources/pom.xml
- utils/archetypes/settings-bundle-archetype/src/main/resources/archetype-resources/src/main/java/service/impl/HelloWorldSettingsServiceImpl.java
> cherry-pick MOTECH-2805: Fix archetypes have wrong dependency for settings config

- modules/scheduler/scheduler/src/main/resources/webapp/messages/messages.properties
This message is required for MOTECH-2739 on motech-ui
> Added message for MOTECH-2739

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
Changed modal type to danger, to get red color, and deleted space between "Remove task" and "?".
> MOTECH-2719 Fixed delete task modal

- platform/mds/mds-web/src/main/resources/webapp/js/directives.js
MOTECH-2831: Fixed Lookup return multiple entities
> MOTECH-2831: Cherry-pick - Fixed Lookup return multiple entities

- modules/admin/src/main/resources/webapp/messages/messages.properties
> MOTECH-2731: add manageModuleSettings message for new UI

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
*fixed missing bubbles problem
*fixed problem with popping-up window after choosing trigger in task > new
> MOTECH-2716: Fixed task triggers modal

- platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
- platform/mds/mds-web/src/main/resources/webapp/js/directives.js
MOTECH-2860 Missing alerts with messages about validation errors in MDS module
- Restored error messages in MDS module
> MOTECH-2860 Missing alerts with messages about validation errors

- modules/admin/src/main/resources/webapp/messages/messages.properties
- platform/email/src/main/resources/webapp/messages/messages.properties
Added messages required for 
motech/motech-ui#81
> Added required messages

- platform/server-bundle/src/main/resources/webapp/partials/homepage.html
- ui/src/css/index.scss
MOTECH Homepage now is more responsive
> MOTECH-2899 Gap between panels in Motech homepage

- platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-edit-Value-boolean.html
fixed the issue where clear button is enable even if nothing is selected
> MOTECH-2514 Button "clear" should be blocked

- modules/tasks/tasks/src/main/resources/webapp/js/app.js
- modules/tasks/tasks/src/main/resources/webapp/partials/form-filter.html
I used ui.bootstrap to typeahead eventKey in parameters from trigger.
> MOTECH-2942: Add the ability to auto complete task trigger text within a filter

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/TaskActivity.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/dto/TaskActivityDto.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/web/ActivityControllerTest.java
During as conversion task activity to dto we didn't include activity ID.
> Fixed retry task errors.

- modules/tasks/tasks/src/main/resources/webapp/partials/field.html
I fixed the bug which was breaking the bubbles in Object Fields in data source. They are already displayed correctly.
> MOTECH-2927: Hover on Bubble Should Show Full Path

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/partials/form-filter.html
My changes also fixed null pointer exceptions in web console.
#714
> MOTECH-2942: fixes after QA and fix switching manipulation button

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
Now stack trace is shown correctly for each row in task activity.
> MOTECH-2938: Fixed blank stack trace window

- pom.xml
Added detailed view of errors in backward compatibility check
> MOTECH-2868 Added detailed view of errors in backward compatibility check

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/web/ChannelController.java
- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/js/filters.js
- modules/tasks/tasks/src/main/resources/webapp/partials/modals/triggersModal.html
Searching triggers by name is now available.
> MOTECH-2965: Added search on available Triggers List

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/enums/TaskActivityType.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskActivityService.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskActivityServiceImpl.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskTriggerHandler.java
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
- modules/tasks/tasks/src/main/resources/webapp/partials/recent-task-activity.html
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskActivityServiceImplTest.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskTriggerHandlerTest.java
When task was triggered but not executed because of filter, there is proper information in task history displayed.
> MOTECH-2989: Added better indication that Task was Run and Filtered

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/FilterSet.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/dto/FilterSetDto.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskInitializer.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskTriggerHandler.java
- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
- modules/tasks/tasks/src/main/resources/webapp/partials/form-action.html
- modules/tasks/tasks/src/main/resources/webapp/partials/form-filter.html
- modules/tasks/tasks/src/main/resources/webapp/partials/form.html
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskTriggerHandlerTest.java
Added button that allow to add filter below each action. Filter has the same options as the existing task filter. When filter result is false actions below it are not executed.
> MOTECH-2924: Added Filters for Actions in Tasks

- modules/tasks/tasks/src/main/resources/webapp/css/tasks.css
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- modules/tasks/tasks/src/main/resources/webapp/partials/field.html
- modules/tasks/tasks/src/main/resources/webapp/partials/widgets/content-editable-map.html
Enhanced adjustText function and CSS styles in specific situations
> MOTECH-2859 Enhanced adjustText function and CSS styles in specific situations

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/TaskActionInformation.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/dto/TaskActionInformationDto.java
- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/partials/form-action.html
- modules/tasks/tasks/src/main/resources/webapp/partials/form-filter.html
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/json/TaskDeserializerTest.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskServiceImplTest.java
- Corrected displaying custom data source names in the filter dropdown.
- Corrected saving task actions name.
> MOTECH-2970: Fixes after QA.

- modules/tasks/tasks/src/main/resources/webapp/js/util.js
- Fixed name of the action disappearing.
> MOTECH-2970: Corrections after QA.

- modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
- modules/tasks/tasks/src/main/resources/webapp/partials/form.html
> MOTECH-3034: Moved the Hide Value Bubbles option to the sidebar

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/repository/TaskActivitiesDataService.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskActivityService.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskWebService.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskActivityServiceImpl.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskWebServiceImpl.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/web/ActivityController.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/web/GridSettings.java
- modules/tasks/tasks/src/main/resources/webapp/index.html
- modules/tasks/tasks/src/main/resources/webapp/js/app.js
- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
- modules/tasks/tasks/src/main/resources/webapp/partials/tasks-history.html
* Created a separate view for tasks history
* Added filters based on progress, task name and date of execution
* Added a button to retry all the failed tasks in current page
> MOTECH-3006 Added provision to retry multiple tasks at once

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/partials/form-action.html
- modules/tasks/tasks/src/main/resources/webapp/partials/form-data-source.html
- modules/tasks/tasks/src/main/resources/webapp/partials/form.html
MOTECH-3009 This commit significantly reduces time of loading task
> MOTECH-3009 Improved loading task time

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/constants/EventSubjects.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskRetryHandler.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskTriggerHandler.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TasksPostExecutionHandler.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskRetryHandlerTest.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskTriggerHandlerTest.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TasksPostExecutionHandlerTest.java
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TasksTestBase.java
Removed unnecessary code for better readability and added some new tests for new funcionality.
> MOTECH-2982: Simplified code for Task Retries

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/ManipulationType.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/util/KeyEvaluator.java
- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
- modules/tasks/tasks/src/main/resources/webapp/js/util.js
- modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
- modules/tasks/tasks/src/main/resources/webapp/partials/help/manipulation.html
- modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/util/KeyEvaluatorTest.java
- Added a quarter function for datetimes.
- Adjust the unit test for this function.
- Added information about quarter in the "help:modification" in the manipulations modal.
> MOTECH-3042: Added a quarter function for datetimes.

- modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/Task.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/dto/TaskDto.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/json/TaskDeserializer.java
- modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskServiceImpl.java
- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/partials/form.html
Now it is possible to set Days in which task should be active.
> MOTECH-3048: Added Days option to availability windows for tasks

- platform/mds/mds-web/src/main/java/org/motechproject/mds/web/controller/InstanceController.java
1. Created controllers at backend to delete bulk selected instances.
2. Added a checkbox option for entity instances table, for multiple selecting.
3. Created a UI model to delete selected instances.
4. Added "Delete All" Modal with its functionaliy.
5. Change "Delete" Modal message which shows the number of selected instances.
6. Disabled Delete and Delete All button when uncheceked and now instances are present respectively.
Review changes
1. Changed the json-simple library to gson.
2. Removed empty lines.
> MOTECH-2074 Bulk delete in MDS UI

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
> MOTECH-3056 Sort Tasks List Alphabetically

- platform/mds/mds/src/main/java/org/motechproject/mds/builder/MDSConstructor.java
- platform/mds/mds/src/main/java/org/motechproject/mds/builder/impl/MDSConstructorImpl.java
- platform/mds/mds/src/main/java/org/motechproject/mds/domain/EntityDraft.java
- platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/EntityServiceImpl.java
- platform/mds/mds/src/main/resources/db/migration/default/V9__MOTECH-3073.sql
- platform/mds/mds/src/main/resources/db/migration/mysql/V9__MOTECH-3073.sql
- platform/mds/mds/src/test/java/org/motechproject/mds/it/osgi/MdsBundleIT.java
- platform/mds/mds/src/test/java/org/motechproject/mds/it/service/EntityServiceContextIT.java
Bug regarded changing required value and dropping columns
> MOTECH-3073: Fixed not updating table definitons.

- modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
- modules/tasks/tasks/src/main/resources/webapp/partials/form-action.html
> MOTECH-3102 The "Show bubble" checkbox doesn't work properly

- modules/tasks/tasks/src/main/resources/webapp/js/directives.js
Fixed the bug regarding display raw syntax in the tasks module
> MOTECH-3112 Display Raw Syntax Does Not Work

- platform/server-bundle/src/main/java/org/motechproject/server/startup/StartupManager.java
Instead of updating database field platformSettings outside of
transaction, the properties object is used.
Reproduction steps:
1. Set config.source FILE
2. Run Motech
3. NPE during saving motech platform settings is thrown
I do not change logic , I'm using field non-related with database and do the same update process.
> Fixed loading properties in config file mode
