docs/source/get_started/install.sh
docs/source/get_started/installing.rst

statement. The previous installation instructions pointed to the latest version which was locked at 0.24.3, but should have pointed to the latest release. Also recommended stopping tomcat7 while the .war file is downloaded and permissions changed. This ensures that tomcat doesn't try to build while downloading.

MOTECH-1600 Update the install doc to reflect latest release in curl 

---

modules/tasks/tasks/src/main/java/org/motechproject/tasks/repository/TaskActivitiesDataService.java
modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
modules/tasks/tasks/src/main/resources/webapp/js/directives.js
modules/tasks/tasks/src/main/resources/webapp/partials/history.html

Now user can filter task activity by the type (warning, error, Success). When type is ERROR user
have possibility to display stack trace. This commit also removes Lookup annotation from
countByTaskAndActivityTypes method to avoid error in the log.

MOTECH-1894: Filter in the task history

---

pom.xml

The new external osgi bundles release contains OSGified
POI OOXML Schemas bundle, that is required to make POI
library work in OSGi environment.

MOTECH-1860 Bumped external dependencies tag to r030

---

platform/mds/mds/src/main/java/org/motechproject/mds/osgi/MdsBundleWatcher.java
platform/osgi-platform/src/main/java/org/motechproject/server/osgi/util/BundleType.java
platform/osgi-platform/src/main/java/org/motechproject/server/osgi/util/PlatformConstants.java
platform/osgi-platform/src/test/java/org/motechproject/server/osgi/BundleTypeTest.java

Mds web was treated as an mds bundle, so it would stop
concurrently with mds. From now on it is treated as a regular
platform bundle.

MOTECH-1861: Prevent mds-web from timing out

---

docs/source/get_started/model_data/model_data.rst
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/controller/AvailableController.java
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java
platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
platform/mds/mds-web/src/main/resources/webapp/messages/messages.properties
platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-basic-defaultValue-date8.html
platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-basic-defaultValue-datetime8.html
platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-edit-Value-date8.html
platform/mds/mds-web/src/main/resources/webapp/partials/widgets/field-edit-Value-datetime8.html
platform/mds/mds/pom.xml
platform/mds/mds/src/main/java/org/motechproject/mds/annotations/internal/UIFilterableProcessor.java
platform/mds/mds/src/main/java/org/motechproject/mds/dto/TypeDto.java
platform/mds/mds/src/main/java/org/motechproject/mds/helper/JavassistBuilder.java
platform/mds/mds/src/main/java/org/motechproject/mds/util/JavassistUtil.java
platform/mds/mds/src/main/java/org/motechproject/mds/util/TypeHelper.java
platform/mds/mds/src/main/resources/db/migration/default/V42__MOTECH-1411.sql
platform/mds/mds/src/main/resources/db/migration/mysql/V42__MOTECH-1411.sql
platform/mds/mds/src/test/java/org/motechproject/mds/builder/EntityBuilderTest.java
platform/mds/mds/src/test/java/org/motechproject/mds/it/osgi/MdsBundleIT.java
platform/mds/mds/src/test/java/org/motechproject/mds/it/reposistory/AllTypesContextIT.java
platform/mds/mds/src/test/java/org/motechproject/mds/it/service/TypeServiceImplContextIT.java
platform/mds/mds/src/test/java/org/motechproject/mds/service/impl/csv/CsvImporterExporterTest.java
platform/mds/mds/src/test/java/org/motechproject/mds/testutil/FieldTestHelper.java
platform/mds/mds/src/test/java/org/motechproject/mds/util/TypeHelperTest.java
pmd.xml
pom.xml

* JDK for Motech is now 1.8 and requires Java8 to compile and run.
* Changed version of maven-pmd-plugin to 3.5 as old one didn't support JDK 1.8.
* MDS now supports LocalDateTime and LocalDate from java.time.
* DateTime and LocalDate from Joda are available for DDEs exclusively.
* Updated MDS documentation about avaliable types
* Adjusted some tests to cover new java.time types
Change-Id: I0a8363e87cb2ee35e839020b25e096f1271af85f

MOTECH-1411: JDK for Motech set to 1.8 + java.time support for MDS

---

platform/mds/mds-web/src/main/resources/webapp/js/controllers.js

Now after saving changes, field which wasn't added is empty.

MOTECH-1881: Schema editor saving an entity does not refresh the view

---

platform/mds/mds-web/src/main/resources/webapp/js/controllers.js
platform/mds/mds-web/src/main/resources/webapp/partials/modals/export-entity.html

Now the default value is 'currently selected'. Regardless of what user selected
, all the time the default value will be 'currently selected' (also after log out,
log in).

MOTECH-1898: Changes the default value for columns to export.

---

docs/source/deployment/felix_webconsole.rst
docs/source/deployment/index.rst
packaging/deb/pom.xml
packaging/rpm/pom.xml
platform/server/pom.xml
pom.xml

* Documented how to install and use the Felix Web Console
* Removed it from Motech, since it is a security hazard by default

MOTECH-1930: Remove the dependency on FWC and documented how to use it

---

modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskActivityServiceImplTest.java
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/controller/InstanceController.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/controller/InstanceControllerTest.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/rest/MdsRestControllerTest.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/rest/ParamParserTest.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/service/impl/InstanceServiceTest.java
platform/mds/mds/src/main/java/org/motechproject/mds/query/QueryParams.java
platform/mds/mds/src/main/java/org/motechproject/mds/query/QueryUtil.java
platform/mds/mds/src/test/java/org/motechproject/mds/it/osgi/MdsBundleIT.java
platform/mds/mds/src/test/java/org/motechproject/mds/it/service/HistoryServiceContextIT.java
platform/mds/mds/src/test/java/org/motechproject/mds/lookup/LookupExecutorTest.java
platform/mds/mds/src/test/java/org/motechproject/mds/query/QueryUtilTest.java

* Allowed ordering on multiple fields using QueryParams
* In the data-browser, use ID ordering as backup to the provided
one
* Cleaned up some duplications in InstanceController and MdsBundleIT

MOTECH-1931: Fix ordering inconsistencies

---

modules/admin/src/main/java/org/motechproject/admin/web/controller/ServerLogController.java
modules/admin/src/main/resources/webapp/js/controllers.js
modules/admin/src/main/resources/webapp/partials/log.html

This commit improves handling server log on the UI. I changed size of logs to display,
now its 200KB. The size is similar to Jenkins console output,
its approximately 2000 lines. Also I changed html tag from <div> to <pre>.
Thanks to that we don't have to parse plain text.

MOTECH-1899: Improves handling server log on the UI

---

platform/mds/mds-web/pom.xml
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/util/RelationshipDisplayUtil.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/RelationshipDisplayUtilTest.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Car.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Driver.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Factory.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Location.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Manufacturer.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/SafetyPolicy.java

This commit fixes issues viewing instances that have
lazy loaded fields. The Spring controller attempted to
access these fields during serialization to json, what
resulted in JDO exception, due to accessing lazy loaded
fields outside a transaction. The relationships now
have their related fields set to null for display.

MOTECH-1844 Fixed MDS Data browser for lazy loaded fields

---

platform/mds/mds-web/src/main/java/org/motechproject/mds/web/controller/InstanceController.java
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/InstanceService.java
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java
platform/mds/mds-web/src/main/resources/webapp/partials/widgets/entityInstances.html
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/service/impl/InstanceServiceTest.java
platform/mds/mds/src/main/java/org/motechproject/mds/ex/entity/EntityInstancesNonEditableException.java

Now the import button is invisible above the entities grid for readonly entities.
Additionally I disallowed it at the backend.
Conflicts:
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java

MOTECH-1925: Import CSV is not possible for readonly entities

---

platform/mds/mds-web/pom.xml
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java
platform/mds/mds-web/src/main/java/org/motechproject/mds/web/util/RelationshipDisplayUtil.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/RelationshipDisplayUtilTest.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Car.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Driver.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Factory.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Location.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/Manufacturer.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/util/mock/SafetyPolicy.java

This commit fixes issues viewing instances that have
lazy loaded fields. The Spring controller attempted to
access these fields during serialization to json, what
resulted in JDO exception, due to accessing lazy loaded
fields outside a transaction. The relationships now
have their related fields set to null for display.

 MOTECH-1844 Fixed MDS Data browser for lazy loaded fields

---

platform/mds/mds/src/main/java/org/motechproject/mds/repository/MotechDataRepository.java
platform/mds/mds/src/main/java/org/motechproject/mds/service/DefaultMotechDataService.java
platform/mds/mds/src/main/java/org/motechproject/mds/service/MotechDataService.java

In order to be more efficient when evicting one entity only

Add evictOne method to MotechDataRepository

---

platform/mds/mds-web/src/main/resources/webapp/js/controllers.js

This commit fixes the problem. Now special characters (for example '+' before timezone)
are encoded before passing url to http request.

MOTECH-1933: Fixes exporting instances using lookup with DateTime field

---

modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/DayOfWeekSchedulableJob.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerActionProxyServiceImpl.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerDatabaseServiceImpl.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerServiceImpl.java
modules/scheduler/scheduler/src/main/resources/task-channel.json
modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/ParameterType.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/MethodHandler.java

There were two issues with the task-channel.json from the Schedule module.
First one was that the "Schedule repeating job" action was passing the "repeatIntervalInMilliSeconds" argument as "LONG" type instead of the "INTEGER"
The second one was that the "Schedule repeating job with period interval" action was passing the "schedulePeriodRepeatingJob" as the "serviceMethod" parameter instead of the "scheduleRepeatingPeriodJob".
The last issue with the Scheduler action was that the repeating job with period interval was recognised as the repeating job and therefore there were problems with builders casting.

MOTECH-1934: Fixed some issues with Scheduler actions

---

docs/source/get_started/install.sh
docs/source/get_started/installing.rst

This was [recommended by Rob](https://applab.atlassian.net/browse/MOTECH-1889?focusedCommentId=69614&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-69614) because I was getting out of memory errors on MDS Entity creation. The minimum recommended setting is 512MB for CATALINA_OPTS.

MOTECH-1889 Update Install Documentation to set CATALINA_OPTS memory

---

docs/requirements.txt

The Read the Docs documentation is currently failing to build due to our reliance on old dependencies. These commits update the Sphynx version to 1.3.1 as well as the other dependencies on this Sphynx version.
[Here's the link](https://readthedocs.org/projects/motech-project/builds/3406151/) to the passing build on read the docs for this branch.

Fixing the Read the Docs Build

---

platform/mds/mds/src/main/java/org/motechproject/mds/ex/object/ObjectCreateException.java
platform/mds/mds/src/main/java/org/motechproject/mds/ex/object/ObjectUpdateException.java

when creating an instance through the UI (and the log error isn't helpful either)
Added message from ConstraintViolation to Exception message.

MOTECH-1806: Errors pointing to logs when a bean validation fails

---

platform/mds/mds/src/main/java/org/motechproject/mds/domain/Field.java
platform/mds/mds/src/main/java/org/motechproject/mds/jdo/SchemaGenerator.java
platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/MigrationServiceImpl.java
platform/mds/mds/src/main/java/org/motechproject/mds/util/Constants.java
platform/mds/mds/src/main/resources/db/migration/default/V30__MOTECH-1618.sql
platform/mds/mds/src/main/resources/db/migration/mysql/V30__MOTECH-1618.sql
platform/web-security/src/main/resources/db/migration/default/preSchemaGeneration/V2__MOTECH-1942.sql
platform/web-security/src/main/resources/db/migration/mysql/preSchemaGeneration/V2__MOTECH-1942.sql

Since version 0.26 the openId is marked as unique. This
means that empty strings will be recognized as duplicates
and won't be allowed. Until version 0.26 we used to put
empty string as openId if it wasn't provided. This migration
changes all empty openId fields to NULL since they are
allowed, even when unique constraint is placed. Moreover
some other migrations have been fixed.
Conflicts:
platform/mds/mds/src/main/java/org/motechproject/mds/jdo/SchemaGenerator.java

MOTECH-1942 SQL migration fixes 0.25 -> 0.26

---

platform/mds/mds/src/main/java/org/motechproject/mds/util/TypeHelper.java

TypeHelper didn't recognize difference between daylight-saving time and standard time offset
for java.time LocalDateTime type. This fix resolves the issue.

MOTECH-1411: Fix for TypeHelper for daylight-saving/standard time parsing

---

modules/tasks/tasks/src/main/java/org/motechproject/tasks/ex/TaskNameAlreadyExistsException.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskServiceImpl.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskServiceImplTest.java

Added task name validation - the TaskNameAlreadyExistsException will be thrown when attempting to save task with already existing name. Added test for new behaviour.

MOTECH-1964: Validation for task name

---

platform/server/src/main/java/org/motechproject/server/impl/JspBundleLoader.java

in tomcat-7 WebappClassLoader has field "resourceEntries" but in tomcat-8 only its superclass has this field so the object must be casted to its superclass to get "resourceEntries" field

MOTECH-1978: cast WebappClassLoader to its superclass

---

modules/admin/src/main/resources/webapp/index.html
modules/admin/src/main/resources/webapp/partials/bundles.html
modules/admin/src/main/resources/webapp/partials/queue_stats.html
modules/tasks/tasks/src/main/resources/webapp/index.html
modules/tasks/tasks/src/main/resources/webapp/partials/tasks.html
platform/email/src/main/resources/webapp/index.html
platform/mds/mds-web/src/main/resources/webapp/index.html
platform/server-bundle/src/main/resources/webapp/js/controllers.js
platform/web-security/src/main/resources/webapp/index.html
utils/archetypes/http-bundle-archetype/src/main/resources/archetype-resources/src/main/resources/webapp/index.html
utils/archetypes/http-bundle-archetype/src/main/resources/archetype-resources/src/main/resources/webapp/js/app.js
utils/archetypes/minimal-bundle-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/motech/applicationContext.xml

Added selectedTabState to server-bundle, which allows to correctly apply 'active' style for tabs with redirect. Changed the way in which 'active' style is set for tabs and breadcrumb to work with new approach. Removed active() method from server-bundle as it is not needed anymore.

MOTECH-1976: Active style for tabs is applied correctly

---

modules/scheduler/scheduler/src/main/resources/webapp/js/directives.js
modules/tasks/tasks/src/main/resources/webapp/js/directives.js
platform/email/src/main/resources/webapp/js/directives.js
platform/mds/mds-web/src/main/resources/webapp/js/directives.js
platform/server-bundle/src/main/resources/webapp/css/jqGrid/ui.jqgrid.override.css

From now headers of columns jqgrid always visible, 
even when no records in the jqgrid.

MOTECH-1983 Headers of columns jqgrid always visible

---

modules/admin/src/main/java/org/motechproject/admin/bundles/DefaultBundleFilter.java
modules/admin/src/test/java/org/motechproject/admin/bundles/DefaultBundleFilterTest.java

This bundle should not be managed by users, stopping it can break
the system.

MOTECH-1999: Remove motech-osgi-platform from admin module management

---

modules/admin/src/main/java/org/motechproject/admin/jmx/MBeanService.java
modules/admin/src/main/java/org/motechproject/admin/jmx/MotechMBeanServer.java
modules/admin/src/test/java/org/motechproject/admin/jmx/MBeanServiceTest.java

Reafctored way in which JMX mBeanName and destination properties are builded, so they will have correct values for newer versions of ActiveMQ, as for 5.8+ naming changed and caused errors in Queues and Topic tabs.

MOTECH-1995: Queues and Topic tabs work with all versions of ActiveMQ

---

platform/server-bundle/src/main/java/org/motechproject/server/CommonsDataProvider.java
platform/server-bundle/src/main/java/org/motechproject/server/commons/PlatformCommons.java
platform/server-bundle/src/main/resources/META-INF/motech/applicationPlatformServerBundle.xml
platform/server-bundle/src/main/resources/META-INF/spring/blueprint.xml
platform/server-bundle/src/main/resources/commons-data-provider.json
platform/server-bundle/src/main/resources/webapp/messages/messages.properties
platform/server-bundle/src/test/java/org/motechproject/server/CommonsDataProviderTest.java

Added CommonsDataProvider to server-bundle. It provides commonly used values such as dates and MOTECH version as a data source for Tasks module.

MOTECH-2017: CommonsDataProvider for Tasks module

---

platform/server-bundle/src/main/resources/webapp/css/index.css

Word labels were getting cut off in long label entries. I changed a line of CSS which is a quick fix to a larger problem of unsemantic data getting into the MOTECH UI.

MOTECH-1992 Task Action> Long Labels Getting Cut Off

---

docs/source/development/dev_setup/docker_install.rst

- Docker Toolbox is the preferred way for running docker using MAC or Win
- Fixed broken link
- Mentioned that the dev setup does not install MOTECH
The inconsistency with image names was fixed in the motech-docker repo.

MOTECH-2025: Multiple fixes to docker documentation

---

platform/mds/mds/src/main/java/org/motechproject/mds/listener/records/BaseListener.java
platform/mds/mds/src/main/java/org/motechproject/mds/listener/records/HistoryListener.java
platform/mds/mds/src/main/java/org/motechproject/mds/listener/records/TrashListener.java

Trash / history listeners will now wait for 5 minutes
for the application context if it is not available
once they are called. This should resolve the issue
with a null pointer exception thrown, due to listeners
executing too early in rare cases.

MOTECH-2026: Added a 5m wait for app ctx in listeners

---

platform/mds/mds/src/main/resources/META-INF/motech/mdsContext.xml

Changed from the default ${ to $flyway{ . Resolves issues with Velocity
strings in migrations getting parsed.

MOTECH-2061: Changed the Flyway placeholder prefix

---

platform/mds/mds/src/main/java/org/motechproject/mds/jdo/MdsJdoAnnotationReader.java

This commit fixes bug, when NucleusException was thrown after schema regeneration
in MDS.
In MDS we use MDS JDO annotation reader, which extends the regular
JDOAnnotationReader from datanucleus. This class was introduced because
regular reader would not read field annotations for metadata if there was
no class level JDO annotations. In this class we fake the PersistenceCapable
annotation.
It works as expected, however sometimes after schema regeneration
datanucleus read wrong Metadata for classes. This is connected with this reader.
When we are loading entities using MDSClassLoader our reader implementation is
needed to see field annotations, however after package.jdo file is ready,
there is no need to fake PersistenceCapable annotation. It's why I added the
condition with …

MOTECH-2035: Fixes bug after schema regeneration in MDS

---

docs/source/development/dev_setup/dev_install.rst

Installing NodeJS per current instructions downloads and installs an older version, which doesn't work with MOTECH. I've adjusted the docs to mention installing NodeJS in version 5. The NodeJS installation step is taken from the official NodeJS website: https://nodejs.org/en/download/package-manager/

Updated dev install docs to use correct NodeJS version

---

modules/tasks/tasks-test-utils/pom.xml

After adding the @Transactional annotation to the TaskTriggerHandler, we need
to add some import packages to motech-task-test-utils module. Now integration
tests which use AbstractTaskBundleIT will work correctly.
I've already checked Commcare ITs and Schedule-tracking IT

MOTECH-2108: Fixes integration tests which use AbstractTaskBundleIT

---

modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/CronSchedulableJob.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/RepeatingPeriodSchedulableJob.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/RepeatingSchedulableJob.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/contract/RunOnceSchedulableJob.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/MotechSchedulerService.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerActionProxyServiceImpl.java
modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/service/impl/MotechSchedulerServiceImpl.java
modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/JobStorePerformanceAssessment.java
modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/domain/TestRunOnceSchedulableJob.java
modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerDatabaseServiceImplBundleIT.java
modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/MotechSchedulerServiceImplBundleIT.java
modules/scheduler/scheduler/src/test/java/org/motechproject/scheduler/it/SchedulerBundleIT.java
platform/commons-date/src/main/java/org/motechproject/commons/date/util/DateUtil.java
platform/commons-date/src/test/java/org/motechproject/commons/date/util/DateUtilTest.java

* The contract was changed to use Joda instead
of java.util.Date
* For now we are holding off from migrating to
Java 8 time handling completely

MOTECH-1411: Scheduler API uses now Joda time

---

docs/source/get_started/model_data/model_data.rst
platform/mds/mds/pom.xml
platform/mds/mds/src/main/java/org/motechproject/mds/MDSInitializer.java
platform/mds/mds/src/main/java/org/motechproject/mds/config/MdsConfig.java
platform/mds/mds/src/main/java/org/motechproject/mds/domain/MigrationMapping.java
platform/mds/mds/src/main/java/org/motechproject/mds/jdo/SchemaGenerator.java
platform/mds/mds/src/main/java/org/motechproject/mds/osgi/MdsBundleWatcher.java
platform/mds/mds/src/main/java/org/motechproject/mds/repository/AllMigrationMappings.java
platform/mds/mds/src/main/java/org/motechproject/mds/service/MigrationService.java
platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/MigrationServiceImpl.java
platform/mds/mds/src/main/java/org/motechproject/mds/util/Constants.java
platform/mds/mds/src/main/resources/META-INF/motech/mdsContext.xml
platform/mds/mds/src/main/resources/db/migration/default/V36__MOTECH-1412.sql
platform/mds/mds/src/main/resources/db/migration/mysql/V36__MOTECH-1412.sql
platform/mds/mds/src/test/java/org/motechproject/mds/jdo/SchemaGeneratorTest.java
platform/mds/mds/src/test/java/org/motechproject/mds/service/impl/MigrationServiceTest.java
platform/mds/mds/src/test/resources/migration/V1__Test1.sql

The so called "module migrations" allow modules to define migrations, that run after MDS generates tables backing up created entities. The modules should expose their migrations in their resource directory, under db/migrations/(default/mysql). Those migrations will be copied to the .motech directory and ran after MDS generates schema.

MOTECH-1412: Flyway migrations can run after MDS generates entity schema

---

ui/src/css/index.css

There are two exactly the same styles in index.css and bootstrap-page.css.
It means that after building we've got duplicate style in motech.css.
Because of that in the error page there is a problem with overridding this style.
It looks like a background color of the first one is overridden, however the
second duplicated is not. It's why we can see blue color instead of red.
This commit fixes this bug.

MOTECH-2111: Changes color in the error screen to red

---

ui/gulpfile.js/tasks/css.js
ui/package.json

CSS styles in IE9 were breaking because there were too many selectors in the CSS file. BlessCss is able to split the css files properly.

MOTECH-2105 IE9 CSS Breaking

---

platform/mds/mds/src/main/java/org/motechproject/mds/domain/Field.java
platform/mds/mds/src/main/java/org/motechproject/mds/domain/UserPreferences.java
platform/mds/mds/src/main/java/org/motechproject/mds/dto/UserPreferencesDto.java
platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/EntityServiceImpl.java
platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/UserPreferencesServiceImpl.java
platform/mds/mds/src/main/resources/db/migration/default/V45__MOTECH-2103.sql
platform/mds/mds/src/main/resources/db/migration/mysql/V45__MOTECH-2103.sql
platform/mds/mds/src/test/java/org/motechproject/mds/it/service/EntityServiceContextIT.java
platform/mds/mds/src/test/java/org/motechproject/mds/service/impl/UserPreferencesServiceTest.java

First of all, I changed collection type used in UserPreference for
selected/unselected fields. Now we use Set instead of List, which means
that we will not see duplicated rows in this tables.
Secondly, I have overridden hashCode() and equals() methods for Field class.
Now it should always properly remove Field objects from collection.

MOTECH-2103: Improves grid selection fields mechanism

---

modules/admin/src/main/java/org/motechproject/admin/internal/service/impl/SettingsServiceImpl.java
modules/admin/src/main/java/org/motechproject/admin/settings/SettingsOption.java
modules/admin/src/test/java/org/motechproject/admin/internal/service/impl/SettingsServiceTest.java

* Check for null
* Added a contructor to SettingsOptions (why should we need to use a
map entry?)

MOTECH-2057: Prevent saving "null" String in settings

---

ui/src/css/select2.css

The CSS for Select2 was causing 404 errors because they requested icons that were located somewhere else. The new CSS file corrects those paths.

MOTECH-2113 Changed Select2 icon paths

---

platform/mds/mds-web/src/main/java/org/motechproject/mds/web/service/impl/InstanceServiceImpl.java
platform/mds/mds-web/src/test/java/org/motechproject/mds/web/service/impl/InstanceServiceTest.java
platform/mds/mds/src/main/java/org/motechproject/mds/dto/FieldDto.java

We no longer auto populate the owner and creator fields.
With the values prepopulated, the validation of modifications to
readonly fields would fail.

MOTECH-2178: Fixed issue with readonly, hidden & auto-gen fields

---

ui/src/js/bootstrap-fileUpload.js

It turned out that not only Import schema file wasn't working. All import file buttons wasnt responding. After some research it turned out bootstrap-fileupload.js was missing after MOTECH-2022. 
Added file to ui/src/js.

MOTECH-2120: added missing library for uploading files

---

modules/tasks/tasks/src/main/resources/webapp/js/directives.js

A multiple isolated scope warning was showing up in the scheduler module. This was caused by the Droppable directive in the tasks module having an isolated scope (which it didnt even use).

MOTECH-2175 Removed isolated scope on tasks droppable directive

---

modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskContext.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/TaskContextTest.java

Now a task data source supports boolean getter 'is...()'.
Note: for Boolean (object wrapper for boolean) you should use getter 'get...()'. Here: http://piotrnowicki.com/2011/01/javabeans-getters-with-boolean-type/ you can find some information about boolean/Boolean getter.

MOTECH-2187: Adds support for boolean getter 'is...()' in Task data source

---

docs/source/modules/email.rst
modules/admin/src/main/java/org/motechproject/admin/notification/EmailNotifier.java
modules/admin/src/test/java/org/motechproject/admin/notification/EmailNotifierTest.java
platform/email/pom.xml
platform/email/src/main/java/org/motechproject/email/domain/Mail.java
platform/email/src/main/java/org/motechproject/email/json/MailDeserializer.java
platform/email/src/main/java/org/motechproject/email/service/EmailSenderService.java
platform/email/src/main/java/org/motechproject/email/service/impl/EmailSenderServiceImpl.java
platform/email/src/main/java/org/motechproject/email/service/impl/MotechMimeMessagePreparator.java
platform/email/src/main/java/org/motechproject/email/service/impl/SendEmailEventHandlerImpl.java
platform/email/src/main/java/org/motechproject/email/web/SendEmailController.java
platform/email/src/test/java/org/motechproject/email/it/EmailBundleIT.java
platform/email/src/test/java/org/motechproject/email/json/MailDeserializerTest.java
platform/email/src/test/java/org/motechproject/email/service/impl/EmailSenderServiceTest.java
platform/email/src/test/java/org/motechproject/email/service/impl/MotechMimeMessagePreparatorTest.java
platform/email/src/test/java/org/motechproject/email/service/impl/SendEmailEventHandlerImplTest.java
platform/email/src/test/java/org/motechproject/email/web/SendEmailControllerTest.java

* Moved contract.Mail to domain.Mail, in order to reduce package export.
* Changed EmailSenderService's method send. It wasn't necessary to send method  contained Mail parameter. I changed it and now send method has four string parameters. Now to use platform-email doesn't need to import two classes, but only one, EmailSenderService.

MOTECH-2089: Clean up the Email API

---

platform/server/pom.xml
pom.xml

After making Tasks dependency in Scheduler module optional, the build order of the modules has changed and made "motech-platform-server" remove some of the modules build before it. MOTECH build will now clean .motech/bundles directory before building any of the modules.

Fix for missing Tasks module after building MOTECH [master]

---

platform/server/pom.xml
pom.xml

After making Tasks dependency in Scheduler module optional, the build order of the modules has changed and made "motech-platform-server" remove some of the modules build before it. MOTECH build will now clean .motech/bundles directory before building any of the modules.

Fix for missing Tasks module after building MOTECH [0.28.X]

---

modules/admin/src/test/java/org/motechproject/admin/it/AdminBundleIT.java

test AdminBundleIT.testUploadBundleFromRepository causes errors when something is changed in API. I faced with this problem during https://github.com/motech/motech/pull/359.
This test uses CMS-Lite module which has dependencies to server-api.  I think that using bundle from motech is better than from external module.

FIX Remove dependency int AdminBundleIT test from cms-lite module

---

platform/config-core/src/main/java/org/motechproject/config/core/domain/BootstrapConfig.java

Currently it creates the Motech dir as literally ${
This currently reproducible for module upload

Fix broken parsing of Motech dir

---

platform/email/src/main/java/org/motechproject/email/service/EmailAuditService.java
platform/email/src/main/java/org/motechproject/email/service/impl/EmailAuditServiceImpl.java
platform/email/src/main/java/org/motechproject/email/service/impl/PurgeEmailEventHandlerImpl.java

@MotechListener cannot be @Transactional - the beans gets picked up
two times by the event module.

MOTECH-2270: Fixed double event handling in the email purger

---

platform/event/src/main/java/org/motechproject/event/listener/proxy/EventAnnotationBeanPostProcessor.java
platform/event/src/test/java/org/motechproject/event/it/EventHandlerAnnotationProcessorBundleIT.java
platform/event/src/test/java/org/motechproject/event/osgi/TestHandlerProxied.java
platform/event/src/test/resources/META-INF/spring/testEventBundleContext.xml

In 'problem description' I describe briefly how it works and how my changes fix the problem. If someone is more curious in section 'understanding proxy usage in Spring' I describe more precisely how it works (pictures and information are from https://spring.io/blog/2012/05/23/transactions-caching-and-aop-understanding-proxy-usage-in-spring). Example 3 and 4, which are mentioned in briefly description are in section 'Understanding proxy usage in Spring'.
If someone annotates method with @MotechListener, the event module will register this method as a listener for subject. By default there will be normal object under the spring bean. However if in the bean is at least one @Transactional annotation (there is no need this two annotations are on the same method), under the bean will be spring …

MOTECH-2297: Prevents double listener registration for proxied beans

---

ui/package.json

Recently gulp-bless version has been updated to 3.1.0. This version doesn't work
properly with Motech using css files. I changed bower dependency to use version
3.0.1 not the latest one.

Fixes Motech build [0.28.X]

---

platform/mds/mds/pom.xml

This package contains classes, that provide some util methods,
that might be used by other modules. One of such examples is
retrieving interface name for data service, which is used in 
MDS performance tests.

Bring back javassist export in MDS

---

modules/tasks/tasks/src/main/java/org/motechproject/tasks/compatibility/TaskMigrationManager.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/compatibility/TaskMigrator.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/compatibility/impl/ProviderNameTaskMigrator.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/DataSource.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/KeyInformation.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/TaskConfig.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/ex/ProviderNotFoundException.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskTriggerHandler.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskServiceImpl.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/validation/TaskDataProviderValidator.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/validation/TaskValidator.java
modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
modules/tasks/tasks/src/main/resources/webapp/js/services.js
modules/tasks/tasks/src/main/resources/webapp/js/util.js
modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
modules/tasks/tasks/src/main/resources/webapp/partials/form.html
modules/tasks/tasks/src/main/resources/webapp/partials/widgets/string-manipulation-format.html
modules/tasks/tasks/src/test/java/org/motechproject/tasks/compatibility/TaskMigrationManagerTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/compatibility/impl/ProviderNameTaskMigratorTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/domain/KeyInformationTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/it/TasksBundleIT.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/json/TaskDeserializerTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/TaskFilterExecutorTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskServiceImplTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/validation/TaskDataProviderValidatorTest.java
modules/tasks/tasks/src/test/resources/mrs-test-data-provider.json
modules/tasks/tasks/src/test/resources/new-task-version.json
modules/tasks/tasks/src/test/resources/task-data-provider.json

Using IDs was a wrong design decision here, they cause a plethora of issues. Compatibility for old tasks is retained thanks to the introduction of a task migrator mechanism. Moreover, a fix for tasks event listeners not being unregistered was also introduced.

[0.27.X] MOTECH-2316: Switching provider IDs used in tasks to provider names

---

platform/server-bundle/src/main/resources/commons-data-provider.json

After adding name validation to tasks data provider, names can only consist of
letters, numbers, - and _. So the name for motech commons data provider must be
change to MOTECH-Commons.

MOTECH-2316: Fixed Motech-Commons data provider name [0.28.X]

---

platform/server-bundle/src/main/resources/commons-data-provider.json

After adding name validation to tasks data provider, names can only consist of
letters, numbers, - and _. So the name for motech commons data provider must be
change to MOTECH-Commons.

MOTECH-2316: Fixed Motech-Commons data provider name

---

modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/util/DataSourceObject.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/util/TaskContext.java
modules/tasks/tasks/src/main/resources/webapp/js/directives.js
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskTriggerHandlerTest.java

Warning about null object of given type is shown only once in recent task activity.
Message of warning specifies object of what type cannot be found.

MOTECH-2389: Fixed more than one same warning in Recent Task Activity

---

platform/web-security/src/main/resources/webapp/css/websecurity.css
platform/web-security/src/main/resources/webapp/messages/messages.properties
platform/web-security/src/main/resources/webapp/partials/permission.html

Added delete option for all permissions in Security (permission.html, websecurity.css). If permission is default delete option is disabled and an appropriate message is shown when 'delete' is hovered.
Added content for the message in messages.properties.

MOTECH-2390: Fixed delete option for permissions in WebSecurity

---

packaging/deb/src/main/debian/motech-base/DEBIAN/control
packaging/deb/src/main/debian/motech-base/etc/init.d/motech

Since 0.28.X Motech needs Java 8, so I updated paths for JDK. Now it reflects
only Java 8 dirs. Additionally I added Java 8 as dependency in daemon config.

MOTECH-2121: Adjusted deb packaging config

---

platform/config-core/src/test/java/org/motechproject/config/core/domain/ConfigLocationTest.java

It seams that URL encoding on Jenkins sometimes fails, so test no more uses
URL

MOTECH-2348: comparing files path without URL conversion

---

platform/mds/mds-web/src/main/java/org/motechproject/mds/web/util/query/QueryParamsBuilder.java

The bug regards lookups which use related lookup field. During execution on the UI
by default there is added a default order for a lookup using its fields. The problem
occurs when this field is a related collection. I know it is not easy to understand,
so let use an example.
@Entity
Author {
String name
}
@Entity
Book {
@Field
List<Author> authors
@Field
Author mainAuthor
}
If we execute a lookup 'By Authors name' the error will pop out. Because jdo
query looks like the following:
... ORDER BY authors.name ascending ...
However should be :
... ORDER BY elementauthorsname.name ascending ...
A lookup 'By Main Author name' works properly.
I have tried to separate this two cases, however it requires using some magic code.
Moreover I think that sorting by related field does not make sense, …

MOTECH-2407: Fixed execution of lookup with related field on the UI [0.27.X]

---

platform/mds/mds-web/src/main/java/org/motechproject/mds/web/util/query/QueryParamsBuilder.java

The bug regards lookups which use related lookup field. During execution on the UI
by default there is added a default order for a lookup using its fields. The problem
occurs when this field is a related collection. I know it is not easy to understand,
so let use an example.
@Entity
Author {
String name
}
@Entity
Book {
@Field
List<Author> authors
@Field
Author mainAuthor
}
If we execute a lookup 'By Authors name' the error will pop out. Because jdo
query looks like the following:
... ORDER BY authors.name ascending ...
However should be :
... ORDER BY elementauthorsname.name ascending ...
A lookup 'By Main Author name' works properly.
I have tried to separate this two cases, however it requires using some magic code.
Moreover I think that sorting by related field does not make sense …

MOTECH-2407: Fixed execution of lookup with related field on the UI

---

modules/scheduler/scheduler/src/main/resources/task-channel.json
modules/scheduler/scheduler/src/main/resources/webapp/messages/messages.properties

- Fixed the name of the RepeatingPeriodJob.
- Changed parameter type for INTEGER in repeatIntervalInMilliSeconds in RepeatingJob.
- Fixed the name of the message used when adding action for Scheduler in Task module for proper displaying.
Now it is possible to Schedule RepeatingJob and RepeatingPeriodJob in Task action.

MOTECH-2447: Fixed two Scheduler Task actions in Scheduler [0.27.X]

---

docs/source/get_started/installing.rst

The install doc had an error with the restructured text ..note annotation and an error that caused the curl to fail when downloading the .war file from nexus.

MOTECH-1600 fixing two errors in the install doc.

---

platform/event/src/main/java/org/motechproject/event/MotechEvent.java
platform/event/src/main/java/org/motechproject/event/exception/CallbackServiceNotFoundException.java
platform/event/src/main/java/org/motechproject/event/listener/EventCallbackService.java
platform/event/src/main/java/org/motechproject/event/listener/impl/EventListenerTree.java
platform/event/src/main/java/org/motechproject/event/listener/impl/ServerEventRelay.java
platform/event/src/test/java/org/motechproject/event/it/EventBundleIT.java
platform/event/src/test/java/org/motechproject/event/listener/impl/ServerEventRelayTest.java

This commit adds the ability to register callback services, that
will be invoked when the execution of a MotechEvent is finished.
The service must implement the EventCallbackService and provide
a callback name, that must be also included in the MotechEvent.
The interface provides two methods - one for success callbacks
and another one for failure callbacks.

MOTECH-2296 Ability to register callbacks to MotechEvents

---

ui/src/js/auth-interceptor.js

I've started adding code to catch the loss of an authenticated session in MOTECH.
This solution works for Ajax queries, but I have not figured out how to make it work when resources are loaded -- as in the case of loading a new module with ocLazyLoad
The new MOTECH-UI uses a different process to authenticate a user, so this PR is targeting the 'legacy' UI and hopes to provide a better experience than the page simply breaking.
I would love opinions about:
(A) MOTECH should show an error message when a user's session is lost
(B) Where we should insert code in the module loading process to catch failed (redirected) resources
-- 1) Before loading a module, ping getUser to verify session (easy, but makes code less specific)
-- 2) See if ocLazyLoad promise knows the redirect happened (not sure …

Catch loss of authenticated session in UI

---

platform/mds/mds-web/pom.xml

There's a missing dependency in mds-web. This bug was fixed after that dependency was added.

MOTECH-2569 Fixed the bug related to adding existing related instance

---

modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskActionExecutor.java

KeyEvaluator holds the current task state - the task context, yet it
was stored as a variable by the task action executor which is a
Sprint singleton. This would cause concurrency issues.

MOTECH-2622: Fixed concurrency issue in tasks

---

modules/tasks/tasks/src/main/resources/webapp/js/controllers.js

These were improperly replaced, which caused issues on Chrome
and IE.

MOTECH-2627: Don't replace custom task fields with bubbles

---

platform/mds/mds-web/src/main/resources/webapp/partials/widgets/entityInstances.html

Fixed the issue where the lookup button is enabled even if the lookup filter is empty.

MOTECH-2216: Lookup button is disabled when lookup filter is empty

---

modules/scheduler/scheduler/src/main/java/org/motechproject/scheduler/listener/MotechSchedulerListener.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/constants/EventDataKeys.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/TaskActivity.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/TaskActivityType.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/domain/mds/task/TaskExecutionProgress.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/TaskActivityService.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskActionExecutor.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskActivityServiceImpl.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskRetryHandler.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TaskTriggerHandler.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TasksEventCallbackService.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/impl/TasksPostExecutionHandler.java
modules/tasks/tasks/src/main/java/org/motechproject/tasks/service/util/TaskContext.java
modules/tasks/tasks/src/main/resources/META-INF/spring/blueprint.xml
modules/tasks/tasks/src/main/resources/webapp/js/controllers.js
modules/tasks/tasks/src/main/resources/webapp/js/directives.js
modules/tasks/tasks/src/main/resources/webapp/messages/messages.properties
modules/tasks/tasks/src/main/resources/webapp/partials/recent-task-activity.html
modules/tasks/tasks/src/test/java/org/motechproject/tasks/it/TaskActivitiesDataServiceBundleIT.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskActionExecutorTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskActivityServiceImplTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskRetryHandlerTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TaskTriggerHandlerTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TasksPostExecutionHandlerTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/impl/TasksTestBase.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/util/TaskContextTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/service/util/TaskFilterExecutorTest.java
modules/tasks/tasks/src/test/java/org/motechproject/tasks/web/ActivityControllerTest.java
platform/event/src/main/java/org/motechproject/event/listener/impl/ServerEventRelay.java
platform/event/src/test/java/org/motechproject/event/listener/impl/ServerEventRelayTest.java

* MOTECH-2296 Task retries for event-based actions
This commit enhances the task retries for the event-based
task actions. Default event system retries are no longer
invoked for task actions. The event module allows to register
event callbacks now, that will be invoked when the event
is handled. Moreover, the Task module now keeps the track
of the task executions.
* MOTECH-2296 Review comments incorporation
* MOTECH-2296 Small refactor
* MOTECH-2296 Test fixes
* MOTECH-2296 Resolved conflicts and small fixes
* MOTECH-2296: Fixed multiply reply count and bubbles parameters
* MOTECH-2296: Changed condition
* MOTECH-2296: Checkstyle...
* MOTECH-2296: Added trigger params to event - without fixed tests
* MOTECH-2296: Added condition to adding task params only for events

MOTECH-2296: Task retries for event-based actions 0.29.X Port

---

docs/source/development/dev_setup/dev_install.rst

The NodeJS 5.x version we were recommending users install is deprecated. The current LTS is 4.x

MOTECH-2734 Changed NodeJS install version to 4.x

---

docs/source/development/dev_setup/dev_install.rst

MOTECH 0.29 is over 78MB when compiled, so tomcat fails unless this value is higher

Update dev install docs with larger upload value

---

platform/mds/mds-web/src/main/resources/webapp/js/directives.js

`scope.field.value = value;` could not pass function safeApply

MOTECH-2336: Fixed error during deleting "Key/Value Pairs" from MDS

---

.gitignore

When I was doing some ticket I saw that file named velocity.log.1 is attached every time to my commit when I make push on github. Added .log* to .gitignore is repairing this problem.

Extented .gitignore about files which contains .log*

---

platform/mds/mds/src/main/java/org/motechproject/mds/service/impl/history/HistoryServiceImpl.java

Steps to reproduce:
1. Create a notification rule instance (it can be other entity with history enabled)
2. Make changes to instance (history rows will be created)
3. Restart the server
4. Go to history of just created notification rule
Expected:
5. History instance should be properly displayed
Actual:
5. Exception is thrown
The problem regards wrong class loader used by datanucleus to retrieve history instance.
To fix this issue, we have to be sure that proper context class loader is set - the same which loads history class

Fixed mds history class loader bug
